# Generated by Django 5.0.9 on 2024-10-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flavorname', models.CharField(max_length=100)),
                ('img', models.URLField(max_length=255)),
            ],
        ),
    ]
